apiVersion: app/V1
kind: Deployment
metadata: 
 name: entries-service-deployment
spec:
 replicas: 2
 selector:
  matchLabels:
   labels:
    component: entries-service
  spec:
   containers:
    - name: entries-service
     image: prashantdey/completeprojectb14:entriesservicev1.0
     ports:
      - containerPort: 50051
     env:
      - name: HOST
        value: "0.0.0.0"
        name: PORT
        value: "50051"
     resources:
      requests:
       cpu: "200m"
       memory: "256Mi"
      limit:
       cpu: "500m"
       memory: "516Mi"