apiVersion: app/V1
kind: Deployment
metadata: 
 name: mood-api-deployment
spec:
 replicas: 2
 selector:
  matchLabels:
   labels:
    component: mood-api
  spec:
   containers:
    - name: mood-api
     image: prashantdey/completeprojectb14:moodsapiv1.0
     ports:
      - containerPort: 5002
     env:
      - name: MOODS_SERVICE_ADDR
        value: "moods-service-cluster-ip-service:50052"
     resources:
      requests:
       cpu: "200m"
       memory: "256Mi"
      limit:
       cpu: "500m"
       memory: "516Mi"