apiVersion: app/V1
kind: Deployment
metadata: 
 name: stats-api-deployment
spec:
 replicas: 2
 selector:
  matchLabels:
   labels:
    component: stats-api
  spec:
   containers:
    - name: stats-api
     image: prashantdey/completeprojectb14:statsapiv1.0
     ports:
      - containerPort: 5003
     env:
      - name: STATS_SERVICE_ADDR
        value: "stats-service-cluster-ip-service:50053"
     resources:
      requests:
       cpu: "200m"
       memory: "256Mi"
      limit:
       cpu: "500m"
       memory: "512Mi"