apiVersion: app/V1
kind: Deployment
metadata: 
 name: stats-service-deployment
spec:
 replicas: 2
 selector:
  matchLabels:
   labels:
    component: stats-service
  spec:
   containers:
    - name: stats-service
     image: prashantdey/completeprojectb14:statsservicev1.0
     ports:
      - containerPort: 50053
     resources:
      requests:
       cpu: "200m"
       memory: "256Mi"
      limit:
       cpu: "500m"
       memory: "516Mi"